# KNN Algorithm

In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import MinMaxScaler, StandardScaler

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, roc_curve, roc_auc_score

from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

import matplotlib.pyplot as plt
import seaborn as sns

# from sklearn.datasets import load_diabetes

In [2]:
# Initialize all the lists
model_details = []
Testing_accuracy = []
Training_accuracy = []
best_params_list = []

In [3]:
df = pd.read_csv("diabetes.csv")
df

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0        148             50             35        0  33.6   
1         85             66             29        0  26.6   
2        183             64              0        0  23.3   
3        150             66             23       94  28.1   
4        150             40             35      168  43.1   
..       ...            ...            ...      ...   ...   
763      101             76             48      180  32.9   
764      122             70             27        0  36.8   
765      121             72             23      112  26.2   
766      126             60              0        0  30.1   
767       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   52        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 8 columns]

In [4]:
df['Outcome'].value_counts()   # imbalance

Outcome
0    500
1    268
Name: count, dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Glucose                   768 non-null    int64  
 1   BloodPressure             768 non-null    int64  
 2   SkinThickness             768 non-null    int64  
 3   Insulin                   768 non-null    int64  
 4   BMI                       768 non-null    float64
 5   DiabetesPedigreeFunction  768 non-null    float64
 6   Age                       768 non-null    int64  
 7   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(6)
memory usage: 48.1 KB


# EDA

# Feature Engineering

## Feature scaling

## 1. Normalization (0 to 1)

In [6]:
x_df = df.drop("Outcome", axis=1)
x_df.head()

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0      148             50             35        0  33.6   
1       85             66             29        0  26.6   
2      183             64              0        0  23.3   
3      150             66             23       94  28.1   
4      150             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   52  
3                     0.167   21  
4                     2.288   33

In [7]:
# Create instance of scalar
normal_scalar = MinMaxScaler()

array = normal_scalar.fit_transform(x_df)

# Create dataframe again
x_normal_df = pd.DataFrame(array, columns=x.columns)
x_normal_df

NameError: name 'x' is not defined

In [ ]:
x_df.describe()

In [ ]:
x_148 = (148 - 0.000000)/(199.000000 - 0.000000)
x_148

In [ ]:
x_85 = (85 - 0.000000)/(199.000000 - 0.000000)
x_85

In [ ]:
fit --> 
transform --> Test, train 
fit_transform --> fit + transfer

## 2. Standardization (-3 to 3)

In [8]:
std_scalar = StandardScaler()

array = std_scalar.fit_transform(x_df)

x_std_df = pd.DataFrame(array, columns=x.columns)
x_std_df

NameError: name 'x' is not defined

# Train Test Split

In [9]:
# Original dataset
x = df.drop("Outcome", axis=1)
y = df["Outcome"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=12, stratify=y)

model_details.append("Regular Model")

In [10]:
# For Normalization
x = x_normal_df.copy()
y = df["Outcome"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=12, stratify=y)
model_details.append("Normalized Model")

NameError: name 'x_normal_df' is not defined

In [11]:
# For Satndardization
x = x_std_df.copy()
y = df["Outcome"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=12, stratify=y)
model_details.append("Satndardized Model")

NameError: name 'x_std_df' is not defined

# Model Training

In [12]:
knn_clf = KNeighborsClassifier()
knn_clf.fit(x_train, y_train)

KNeighborsClassifier()

# Evaluation

In [13]:
# Testing Data Evaluation
y_pred = knn_clf.predict(x_test)

cnf_matrix = confusion_matrix(y_pred, y_test)
print("Confusion Matrix:\n",cnf_matrix)

print("*"*84)

accuracy = accuracy_score(y_pred, y_test)
print("Accuracy Score", accuracy)

# We are appending testing accuracy in list
Testing_accuracy.append(accuracy)
print("*"*84)

clf_report = classification_report(y_pred, y_test)
print("Classification report:\n",clf_report)

Confusion Matrix:
 [[102  34]
 [ 23  33]]
************************************************************************************
Accuracy Score 0.703125
************************************************************************************
Classification report:
               precision    recall  f1-score   support

           0       0.82      0.75      0.78       136
           1       0.49      0.59      0.54        56

    accuracy                           0.70       192
   macro avg       0.65      0.67      0.66       192
weighted avg       0.72      0.70      0.71       192



In [14]:
# Training Data Evaluation
y_pred_train = knn_clf.predict(x_train)

cnf_matrix = confusion_matrix(y_pred_train, y_train)
print("Confusion Matrix:\n",cnf_matrix)

print("*"*84)

accuracy = accuracy_score(y_pred_train, y_train)
print("Accuracy Score", accuracy)

# We are appending training accuracy in list
Training_accuracy.append(accuracy)

print("*"*84)

clf_report = classification_report(y_pred_train, y_train)
print("Classification report:\n",clf_report)

Confusion Matrix:
 [[332  66]
 [ 43 135]]
************************************************************************************
Accuracy Score 0.8107638888888888
************************************************************************************
Classification report:
               precision    recall  f1-score   support

           0       0.89      0.83      0.86       398
           1       0.67      0.76      0.71       178

    accuracy                           0.81       576
   macro avg       0.78      0.80      0.79       576
weighted avg       0.82      0.81      0.81       576



In [263]:
best_params_list.append(np.nan)

# Hyperparameter Tunning

In [15]:
# Estimator
knn_clf = KNeighborsClassifier()

# param_grid
hyperparameters = {"n_neighbors" : np.arange(3,30),
                  "p": [1,2]}

gscv_knn_clf = GridSearchCV(knn_clf, hyperparameters, cv = 5)
gscv_knn_clf.fit(x_train, y_train)
gscv_knn_clf.best_estimator_

model_details.append("Hyperparameter_Tunning")

In [17]:
best_params = gscv_knn_clf.best_params_
best_params_list.append(best_params)
best_params

{'n_neighbors': 21, 'p': 1}

In [266]:
# Testing Data Evaluation

# To get best model from hyperparameter tunning
knn_clf = gscv_knn_clf.best_estimator_

y_pred = knn_clf.predict(x_test)

cnf_matrix = confusion_matrix(y_pred, y_test)
print("Confusion Matrix:\n",cnf_matrix)

print("*"*84)
accuracy = accuracy_score(y_pred, y_test)
print("Accuracy Score", accuracy)

# We are appending testing accuracy in list
Testing_accuracy.append(accuracy)
print("*"*84)

clf_report = classification_report(y_pred, y_test)
print("Classification report:\n",clf_report)

Confusion Matrix:
 [[109  34]
 [ 16  33]]
************************************************************************************
Accuracy Score 0.7395833333333334
************************************************************************************
Classification report:
               precision    recall  f1-score   support

           0       0.87      0.76      0.81       143
           1       0.49      0.67      0.57        49

    accuracy                           0.74       192
   macro avg       0.68      0.72      0.69       192
weighted avg       0.78      0.74      0.75       192



In [267]:
# Training Data Evaluation
y_pred_train = knn_clf.predict(x_train)

cnf_matrix = confusion_matrix(y_pred_train, y_train)
print("Confusion Matrix:\n",cnf_matrix)

print("*"*84)
accuracy = accuracy_score(y_pred_train, y_train)
print("Accuracy Score", accuracy)

# We are appending testing accuracy in list
Training_accuracy.append(accuracy)
print("*"*84)

clf_report = classification_report(y_pred_train, y_train)
print("Classification report:\n",clf_report)

Confusion Matrix:
 [[336  86]
 [ 39 115]]
************************************************************************************
Accuracy Score 0.7829861111111112
************************************************************************************
Classification report:
               precision    recall  f1-score   support

           0       0.90      0.80      0.84       422
           1       0.57      0.75      0.65       154

    accuracy                           0.78       576
   macro avg       0.73      0.77      0.75       576
weighted avg       0.81      0.78      0.79       576



In [ ]:
1. Regular Model --> without hyp --> after hyp
2. Normalization Model --> without hyp --> after hyp
3. Satnadardization Model --> without hyp --> after hyp

In [268]:
print("best_params_list",best_params_list,len(best_params_list))

best_params_list [nan, {'n_neighbors': 21, 'p': 1}, nan, {'n_neighbors': 13, 'p': 2}, nan, {'n_neighbors': 17, 'p': 2}] 6


# Overall Accuracy Comparison

In [269]:
comparison_df = pd.DataFrame({"Model_details":model_details, "Training_accuracy":Training_accuracy, "Testing_accuracy":Testing_accuracy, "best_parameters":best_params_list})
comparison_df

Model_details  Training_accuracy  Testing_accuracy  \
0           Regular Model           0.810764          0.703125   
1  Hyperparameter_Tunning           0.767361          0.739583   
2        Normalized Model           0.798611          0.744792   
3  Hyperparameter_Tunning           0.781250          0.739583   
4      Satndardized Model           0.822917          0.755208   
5  Hyperparameter_Tunning           0.782986          0.739583   

               best_parameters  
0                          NaN  
1  {'n_neighbors': 21, 'p': 1}  
2                          NaN  
3  {'n_neighbors': 13, 'p': 2}  
4                          NaN  
5  {'n_neighbors': 17, 'p': 2}

In [270]:
comparison_df["Diffrence_in_%"] = (comparison_df["Training_accuracy"] - comparison_df["Testing_accuracy"])*100
comparison_df

Model_details  Training_accuracy  Testing_accuracy  \
0           Regular Model           0.810764          0.703125   
1  Hyperparameter_Tunning           0.767361          0.739583   
2        Normalized Model           0.798611          0.744792   
3  Hyperparameter_Tunning           0.781250          0.739583   
4      Satndardized Model           0.822917          0.755208   
5  Hyperparameter_Tunning           0.782986          0.739583   

               best_parameters  Diffrence_in_%  
0                          NaN       10.763889  
1  {'n_neighbors': 21, 'p': 1}        2.777778  
2                          NaN        5.381944  
3  {'n_neighbors': 13, 'p': 2}        4.166667  
4                          NaN        6.770833  
5  {'n_neighbors': 17, 'p': 2}        4.340278