In [1]:
import numpy as np

a = np.arange(9)
# print(a)
a = a.reshape(3,3) + 20
a

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

In [11]:
np.argmax(a, axis=None)

8

In [6]:
np.argmin(a, axis=0)

array([0, 0, 0], dtype=int64)

In [5]:
np.argmax(a, axis=1)

array([2, 2, 2], dtype=int64)