# **Creating the array using the numpy array**

## Import the numpy library

In [64]:
import numpy as np 

## Zero dimention array

In [57]:
array0=np.array(5)
print(array0,type(array0),array0.ndim)

5 <class 'numpy.ndarray'> 0


## 1 dimention array

In [55]:
array1=np.array([5])
print(array1,type(array1),array1.ndim)

[5] <class 'numpy.ndarray'> 1


## 2 dimention array

In [72]:
array2=np.array([[5,7],[6,8]])
print(array2,type(array2),array2.ndim)
print(array2.shape)

[[5 7]
 [6 8]] <class 'numpy.ndarray'> 2
(2, 2)


## 3 dimention array

In [73]:
array3= np.array([[[5,8],[6,9]],[[5,3],[6,7]]])
print(array3,type(array3),array3.ndim)
print(array3.shape)


[[[5 8]
  [6 9]]

 [[5 3]
  [6 7]]] <class 'numpy.ndarray'> 3
(2, 2, 2)


## 4 dimentional array

In [69]:
array4=np.array([[[[1],[2]],[[1],[2]]],[[[1],[2]],[[1],[2]]]])
print(array4,type(array4),array4.ndim)
print(array4.shape)


# 1st dimension: Groups of 3D arrays.
# 2nd dimension: Rows of 2D matrices.
# 3rd dimension: Columns of 1D arrays.
# 4th dimension: Individual elements in the arrays.


[[[[1]
   [2]]

  [[1]
   [2]]]


 [[[1]
   [2]]

  [[1]
   [2]]]] <class 'numpy.ndarray'> 4
(2, 2, 2, 1)


## checking the shape of the array 

In [67]:
print(array0.shape)
print(array1.shape)
print(array2.shape)
print(array3.shape)
print(array4.shape)

()
(1,)
(2, 1)
(2, 2, 1)
(2, 2, 2, 1)


In [88]:
array4[1][1]

array([[1],
       [2]])