### NumPy Functions

In [1]:
import numpy as np

In [1]:
import pandas as pd
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_built_with_meson',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_pandas_datetime_CAPI',
 '_pandas_parser_CAPI',
 '_testing',
 '_typing',
 '_version_meson',
 'annota

In [2]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [3]:
len(dir(np))

599

# 10. append

In [ ]:
used to append the value at the end of an array
synatx:
    np.append(array1, value, axis=None)
    
value >> 0D, 1D, 2D ....

# Answer of every array in 1D only
# Flattern the array

In [6]:
array1 = np.array([3,2,4,5])
array2 = np.array([10,20,30,40])
array3 = np.array(100)   

In [7]:
np.append(array1, array3)

array([  3,   2,   4,   5, 100])

In [8]:
np.append(array1, array2)

array([ 3,  2,  4,  5, 10, 20, 30, 40])

In [9]:
lst1 = [1,2,3,4]
lst2 = [4,5,6,7]
lst1 + lst2

[1, 2, 3, 4, 4, 5, 6, 7]

In [10]:
array1 = np.array([3,2,4,5])
array2 = np.array([10,20,30,40])
array1 + array2

array([13, 22, 34, 45])

In [11]:
array1 = np.array([3,2,4,5])   # 1D
array2 = np.array([[10,20],[30,40]])  # 2D

np.append(array1, array2)

array([ 3,  2,  4,  5, 10, 20, 30, 40])

In [12]:
array1 = np.array([[[3,2,4,5]]])   # 3D
array2 = np.array([[10,20],[30,40]])  # 2D

np.append(array1, array2)

array([ 3,  2,  4,  5, 10, 20, 30, 40])

In [ ]:
# axis = 0 --> Rowise
# axis = 1 --> Columnwise

In [14]:
# Rowwise append
array1 = np.array([[3,2],[4,5]])   # 2D
print("array1 -->\n",array1)
array2 = np.array([[10,20],[30,40]])  # 2D
print("array2 -->\n",array2)


np.append(array1, array2, axis=0)

array1 -->
 [[3 2]
 [4 5]]
array2 -->
 [[10 20]
 [30 40]]


array([[ 3,  2],
       [ 4,  5],
       [10, 20],
       [30, 40]])

In [15]:
# Columnwise append
array1 = np.array([[3,2],[4,5]])   # 2D
print("array1 -->\n",array1)
array2 = np.array([[10,20],[30,40]])  # 2D
print("array2 -->\n",array2)


np.append(array1, array2, axis=1)

array1 -->
 [[3 2]
 [4 5]]
array2 -->
 [[10 20]
 [30 40]]


array([[ 3,  2, 10, 20],
       [ 4,  5, 30, 40]])

# 11. Concatenate()

In [ ]:
syntax:
    np.concatenate([a1,a2,a3......], axis=0)
    
# axis = 0 --> bydefault

In [18]:
array1 = np.array([3,2,4,5])
print("array1 -->\n",array1)

array2 = np.array([10,20,30,40])
print("array2 -->\n",array2)

np.concatenate([array1, array2], axis=0)

array1 -->
 [3 2 4 5]
array2 -->
 [10 20 30 40]


array([ 3,  2,  4,  5, 10, 20, 30, 40])

In [19]:
array1 = np.array([3,2,4,5])
print("array1 -->\n",array1)

array2 = np.array([10,20,30,40])
print("array2 -->\n",array2)

np.concatenate([array1, array2], axis=1)  

array1 -->
 [3 2 4 5]
array2 -->
 [10 20 30 40]


AxisError: axis 1 is out of bounds for array of dimension 1

In [25]:
array1 = np.array([[3,2],[4,5]])
print("array1 -->\n",array1)

array2 = np.array([[10,20],[30,40]])
print("array2 -->\n",array2)

array3 = np.array([[100,200],[300,400]])
print("array3 -->\n",array3)

np.concatenate([array1, array2, array3])

array1 -->
 [[3 2]
 [4 5]]
array2 -->
 [[10 20]
 [30 40]]
array3 -->
 [[100 200]
 [300 400]]


array([[  3,   2],
       [  4,   5],
       [ 10,  20],
       [ 30,  40],
       [100, 200],
       [300, 400]])

In [24]:
array1 = np.array([[3,2],[4,5]])
print("array1 -->\n",array1)

array2 = np.array([[10,20],[30,40]])
print("array2 -->\n",array2)

array3 = np.array([[100,200],[300,400]])
print("array3 -->\n",array3)

np.concatenate([array1, array2, array3], axis=1)

array1 -->
 [[3 2]
 [4 5]]
array2 -->
 [[10 20]
 [30 40]]
array3 -->
 [[100 200]
 [300 400]]


array([[  3,   2,  10,  20, 100, 200],
       [  4,   5,  30,  40, 300, 400]])

# 12. for loop

In [26]:
array = np.array([2,3,4,5,6])
array

array([2, 3, 4, 5, 6])

In [27]:
for i in array:
    print("Value is:", i)

Value is: 2
Value is: 3
Value is: 4
Value is: 5
Value is: 6


In [29]:
arr2 = np.array([[2,3],[4,5],[6,7]])

for i in arr2:
    for j in i:
        print("Value is:", j)

Value is: 2
Value is: 3
Value is: 4
Value is: 5
Value is: 6
Value is: 7


In [2]:
import numpy as np
arr3 = np.array([[[2,3],[4,5]],[[20,30],[40,50]]])  # 3D

for i in arr3:
    print(i)
    for j in i:
        for k in j:
            print("Value is:", k)

[[2 3]
 [4 5]]
Value is: 2
Value is: 3
Value is: 4
Value is: 5
[[20 30]
 [40 50]]
Value is: 20
Value is: 30
Value is: 40
Value is: 50


# 14. nditer()

In [ ]:
It will work like a for loop
syntax:
    np.nditer(array)

In [32]:
array = np.array([2,3,4,5,6])

for i in np.nditer(array):
    print("Value is:", i)

Value is: 2
Value is: 3
Value is: 4
Value is: 5
Value is: 6


In [33]:
arr2 = np.array([[2,3],[4,5],[6,7]])

for i in np.nditer(arr2):
    print("Value is:", i)

Value is: 2
Value is: 3
Value is: 4
Value is: 5
Value is: 6
Value is: 7


In [34]:
arr3 = np.array([[[2,3],[4,5]],[[20,30],[40,50]]])  # 3D

for i in np.nditer(arr3):
    print("Value is:", i)

Value is: 2
Value is: 3
Value is: 4
Value is: 5
Value is: 20
Value is: 30
Value is: 40
Value is: 50


# 15. ndenumerate

In [ ]:
synatx:
    np.ndenumerate(array)
    
it will return index of an element and value at that index

In [35]:
array = np.array([2,3,4,5,6])

for i in np.ndenumerate(array):
    print("Value is:", i)

Value is: ((0,), 2)
Value is: ((1,), 3)
Value is: ((2,), 4)
Value is: ((3,), 5)
Value is: ((4,), 6)


In [36]:
arr2 = np.array([[2,3],[4,5],[6,7]])

for i in np.ndenumerate(arr2):
    print("Value is:", i)

Value is: ((0, 0), 2)
Value is: ((0, 1), 3)
Value is: ((1, 0), 4)
Value is: ((1, 1), 5)
Value is: ((2, 0), 6)
Value is: ((2, 1), 7)


In [37]:
arr3 = np.array([[[2,3],[4,5]],[[20,30],[40,50]]])  # 3D

for i in np.ndenumerate(arr3):
    print("Value is:", i)

Value is: ((0, 0, 0), 2)
Value is: ((0, 0, 1), 3)
Value is: ((0, 1, 0), 4)
Value is: ((0, 1, 1), 5)
Value is: ((1, 0, 0), 20)
Value is: ((1, 0, 1), 30)
Value is: ((1, 1, 0), 40)
Value is: ((1, 1, 1), 50)


In [1]:
import numpy as np
array1 = np.array([[3,2],[4,5]])
print("array1 -->\n",array1)

array2 = np.array([[10,20],[30,40]])
print("array2 -->\n",array2)
np.dot(array1,array2)

array1 -->
 [[3 2]
 [4 5]]
array2 -->
 [[10 20]
 [30 40]]


array([[ 90, 140],
       [190, 280]])

In [ ]:
np.