# Numpy

In [1]:
import numpy as np

arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [6]:
arr = np.array([[1,2,3,4]])
arr.ndim

2

In [9]:
arr = np.array([[(1,2),(3,4)]])
arr.ndim

3

In [10]:
arr = np.array([[1,2,3,4,5,6]])
arr

array([[1, 2, 3, 4, 5, 6]])

In [11]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
arr.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [14]:
arr.reshape(2,3,1)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [15]:
l = [10,12,14,15,17,19]

l * 2

[10, 12, 14, 15, 17, 19, 10, 12, 14, 15, 17, 19]

In [16]:
# Multiply by 2
output = [i*2 for i in l]
output

[20, 24, 28, 30, 34, 38]

In [17]:
# by using lambda 
a = list(map(lambda x: x*2, l))
a

[20, 24, 28, 30, 34, 38]

In [21]:
# by using array
import numpy as np
arr = np.array(l)
b = arr * 2

output = b.tolist()
output

[20, 24, 28, 30, 34, 38]

In [22]:
# division

l = [10,12,14,15,17,19]
arr = np.array(l)
b = arr / 2

output = b.tolist()
output

[5.0, 6.0, 7.0, 7.5, 8.5, 9.5]

In [23]:
# Floor division

l = [10,12,14,15,17,19]
arr = np.array(l)
b = arr // 2

output = b.tolist()
output

[5, 6, 7, 7, 8, 9]

In [24]:
# square

l = [10,12,14,15,17,19]
arr = np.array(l)
b = arr ** 2

output = b.tolist()
output

[100, 144, 196, 225, 289, 361]

In [25]:
# cube

l = [10,12,14,15,17,19]
arr = np.array(l)
b = arr ** 3

output = b.tolist()
output

[1000, 1728, 2744, 3375, 4913, 6859]

In [26]:
# remainder

l = [10,12,14,15,17,19]
arr = np.array(l)
b = arr % 3

output = b.tolist()
output

[1, 0, 2, 0, 2, 1]

# Add two arrays

In [ ]:
Condition:
    shape of both the arrays should be same

In [32]:
a1 = np.array([10,20,30,40])
a2 = np.array([1,2,3,4])

a1 + a2

array([11, 22, 33, 44])

In [2]:
import numpy as np
a1 = np.array([[10,20],[30,40]])
a2 = np.array([[1,2],[3,4]])

print(a1+a2)
np.add(a1,a2)  # a1 + a2

[[11 22]
 [33 44]]


array([[11, 22],
       [33, 44]])

### Multiplication of arrays

In [29]:
a1 = np.array([10,20,30,40])
a2 = np.array([1,2,3,4])

a1 * a2

array([ 10,  40,  90, 160])

In [31]:
a1 = np.array([[10,20],[30,40]])
a2 = np.array([[1,2],[3,4]])

np.multiply(a1, a2)

array([[ 10,  40],
       [ 90, 160]])

### sum of elements of an array

In [33]:
a1 = np.array([[10,20],[30,40]])
np.sum(a1)

100

### Matrix addition

In [ ]:
Matrix >> 2D array

In [34]:
a1 = np.array([[10,20],[30,40]])
a2 = np.array([[1,2],[3,4]])

print("Array 1 -->", a1)
print("Array 2 -->", a2)

np.add(a1,a2)

Array 1 --> [[10 20]
 [30 40]]
Array 2 --> [[1 2]
 [3 4]]


array([[11, 22],
       [33, 44]])

### Matrix Multiplication

In [35]:
a1 = np.array([[10,20],[30,40]])
a2 = np.array([[1,2],[3,4]])

print("Array 1 -->", a1)
print("Array 2 -->", a2)

np.multiply(a1,a2)

Array 1 --> [[10 20]
 [30 40]]
Array 2 --> [[1 2]
 [3 4]]


array([[ 10,  40],
       [ 90, 160]])

### Matrix dot product

In [ ]:
Matrix dot product is possible only when,
No. of columns of 1st matix = No. of rows of 2nd matrix

In [40]:
a1 = np.array([[10,20],[30,40]])
a2 = np.array([[1,2],[3,4]])

print("Array 1 -->\n", a1,a1.shape)
print("Array 2 -->\n", a2, a2.shape)



Array 1 -->
 [[10 20]
 [30 40]] (2, 2)
Array 2 -->
 [[1 2]
 [3 4]] (2, 2)


In [ ]:
# dot product
10*1 + 20*3        10*2 + 20*4
30*1 + 40*3        30*2 + 40*4

In [38]:
a1 = np.array([[10,20],[30,40]])
a2 = np.array([[1,2],[3,4]])

print("Array 1 -->\n", a1)
print("Array 2 -->\n", a2)
np.dot(a1,a2)

Array 1 -->
 [[10 20]
 [30 40]]
Array 2 -->
 [[1 2]
 [3 4]]


array([[ 70, 100],
       [150, 220]])

In [3]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

result = A @ B
print(result)


[[19 22]
 [43 50]]


In [4]:
# Define two matrices
A = [[1, 2], [3, 4]]
B = [[5, 6], [7, 8]]

# Initialize the result matrix with zeros
result = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]

# Perform matrix multiplication
# for i in range(len(A)):
#     for j in range(len(B[0])):
#         for k in range(len(B)):
#             result[i][j] += A[i][k] * B[k][j]

print(result)


[[0, 0], [0, 0]]


In [42]:
a1 = np.array([[10,20],[30,40],[4,6]])
a2 = np.array([[1,2],[3,4]])


print("Array 1 -->\n", a1, a1.shape)
print("Array 2 -->\n", a2, a2.shape)
np.dot(a1,a2)

Array 1 -->
 [[10 20]
 [30 40]
 [ 4  6]] (3, 2)
Array 2 -->
 [[1 2]
 [3 4]] (2, 2)


array([[ 70, 100],
       [150, 220],
       [ 22,  32]])

In [43]:
a1 = np.array([[10,20],[30,40],[4,6]])  #(3,2)
a2 = np.array([[1,2],[3,4]])            #(2,2)
a3 = np.array([[2,3,4],[7,8,9]])        #(2,3)

print("Array 1 -->\n", a1, a1.shape)
print("Array 2 -->\n", a2, a2.shape)
np.dot(a1,a2)

Array 1 -->
 [[10 20]
 [30 40]
 [ 4  6]] (3, 2)
Array 2 -->
 [[1 2]
 [3 4]] (2, 2)


array([[ 70, 100],
       [150, 220],
       [ 22,  32]])

In [47]:
a1 = np.array([[10,20],[30,40],[4,6]])  #(3,2)
a2 = np.array([[1,2],[3,4]])            #(2,2)
a3 = np.array([[2,3,4],[7,8,9]])        #(2,3)

print("Array 1 -->\n", a1, a1.shape)
print("Array 2 -->\n", a2, a2.shape)
np.dot(a1,a3)

Array 1 -->
 [[10 20]
 [30 40]
 [ 4  6]] (3, 2)
Array 2 -->
 [[1 2]
 [3 4]] (2, 2)


array([[160, 190, 220],
       [340, 410, 480],
       [ 50,  60,  70]])