# NumPy Array

In [1]:
import numpy as np

In [2]:
# create empty numpy array
a1 = np.array([])
a1

array([], dtype=float64)

In [ ]:
import numpy as np
arr1 = np.array([1,3,4)
arr1

In [3]:
import numpy as np

array1 = np.array([1,2,3,4,5,6])
print(array1,type(array1),len(array1))

[1 2 3 4 5 6] <class 'numpy.ndarray'> 6


In [4]:
import numpy as np

array1 = np.array([1,2,3,4,5.5,6])
print(array1,type(array1),len(array1))

[1.  2.  3.  4.  5.5 6. ] <class 'numpy.ndarray'> 6


In [5]:
import numpy as np

array1 = np.array([[1,2],[3,4],[5.5,6+2j]])
print(array1,type(array1),len(array1))

[[1. +0.j 2. +0.j]
 [3. +0.j 4. +0.j]
 [5.5+0.j 6. +2.j]] <class 'numpy.ndarray'> 3


In [6]:
import numpy as np

array1 = np.array([1,2,3,4,5.5,6+2j,"a"])
print(array1,type(array1),len(array1))

['1' '2' '3' '4' '5.5' '(6+2j)' 'a'] <class 'numpy.ndarray'> 7


In [7]:
We can covert:
    int --> float
    int --> complex
    float --> int
    float --> complex
    complex ||--> int
    complex ||--> float

SyntaxError: invalid syntax (2492401289.py, line 1)

In [8]:
arr = np.array([3,4,5,6])
arr

array([3, 4, 5, 6])

In [9]:
arr = np.array([3,4,5,6], dtype='float')
arr

array([3., 4., 5., 6.])

In [10]:
arr = np.array([3,4,5,6], dtype='complex')
arr

array([3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j])

In [11]:
arr = np.array([3,4.5,5,6], dtype='int')
arr

array([3, 4, 5, 6])

In [12]:
arr = np.array([3,4.5,5,6], dtype='complex')
arr

array([3. +0.j, 4.5+0.j, 5. +0.j, 6. +0.j])

In [13]:
arr = np.array([3,4.5,5,6+2j], dtype='int')
arr

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'complex'

In [ ]:
arr = np.array([3,4.5,5,6+2j], dtype='float')
arr

In [14]:




arr = np.array([3,4.5,5,6], dtype='object')
arr

array([3, 4.5, 5, 6], dtype=object)

# Dimensions in array

In [15]:
synatx:
    array.ndim

SyntaxError: invalid syntax (1627303787.py, line 1)

## 0-D dimensional array

In [16]:
arr0 = np.array(12)
print(arr0)
print("Dimensions of array are:",arr0.ndim)

12
Dimensions of array are: 0


In [17]:
arr0 = np.array(7.2154)
print(arr0)
print("Dimensions of array are:",arr0.ndim)

7.2154
Dimensions of array are: 0


## 1-D dimensional array

In [18]:
# 1-D >> 1 square bracket

arr1 = np.array([1,2,3,4,5,6])
print(arr1)
print("Dimensions of array is:",arr1.ndim)
print("Shape of 1-D array",arr1.shape)

# 1-D --> made up of no. of 0-D arrays

[1 2 3 4 5 6]
Dimensions of array is: 1
Shape of 1-D array (6,)


In [24]:
# 1-D >> 1 square bracket

arr1 = np.array([1,2.5,3,4,5,6])
print("Dimensions of array is:",arr1.ndim)
arr1

Dimensions of array is: 1


array([1. , 2.5, 3. , 4. , 5. , 6. ])

## 2-D dimensional array

In [26]:
# 2-D >> 2 square bracket

arr2 = np.array([[1,2,3,4,5,6]])
print(arr2)
print("Dimensions of array are:",arr2.ndim)

# 1-D --> made up of no. of 0-D arrays

[[1 2 3 4 5 6]]
Dimensions of array are: 2


In [28]:
# 2-D >> 2 square bracket

arr2 = np.array([[1,2],[3,4],[5,6]])
print(arr2)
print("Dimensions of array are:",arr2.ndim)
print("Shape of array is", arr2.shape)
# 2-D --> made up of no. of 1-D arrays

[[1 2]
 [3 4]
 [5 6]]
Dimensions of array are: 2
Shape of array is (3, 2)


In [29]:
# 2-D >> 2 square bracket

arr2 = np.array([[11,12,13],[3,4,5],[5,6,7]])
print(arr2)
print("Dimensions of array are:",arr2.ndim)
print("Shape of array is", arr2.shape)

# 2-D --> made up of no. of 1-D arrays

[[11 12 13]
 [ 3  4  5]
 [ 5  6  7]]
Dimensions of array are: 2
Shape of array is (3, 3)


In [30]:
# 2-D >> 2 square bracket

arr2 = np.array([[1,2],[3,4]])
print(arr2)
print("Dimensions of array are:",arr2.ndim)
print("Shape of array is", arr2.shape)
# 2-D --> made up of no. of 1-D arrays

[[1 2]
 [3 4]]
Dimensions of array are: 2
Shape of array is (2, 2)


In [31]:
# 2-D >> 2 square bracket

arr2 = np.array([[1,2],[3,4,5]])
print(arr2)
print("Dimensions of array are:",arr2.ndim)
print("Shape of array is", arr2.shape)
# 2-D --> made up of no. of 1-D arrays


# All 0-D elements should be euqul in 1-D array 

[list([1, 2]) list([3, 4, 5])]
Dimensions of array are: 1
Shape of array is (2,)


C:\Users\hp\AppData\Local\Temp\ipykernel_1192\787926024.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr2 = np.array([[1,2],[3,4,5]])


In [34]:
# 2-D >> 2 square bracket

arr2 = np.array([[1,2,5],[3,4,5]])
print(arr2)
print("Dimensions of array are:",arr2.ndim)
print("Shape of array is", arr2.shape)

# 2-D --> made up of no. of 1-D arrays


# All 0-D elements should be euqul in 1-D array 

[[1 2 5]
 [3 4 5]]
Dimensions of array are: 2
Shape of array is (2, 3)


In [35]:
arr2 = np.array([[1,2,5],[3,4,5], [10,20,50]])
print(arr2)
print("Dimensions of array are:",arr2.ndim)
print("Shape of array is", arr2.shape)

[[ 1  2  5]
 [ 3  4  5]
 [10 20 50]]
Dimensions of array are: 2
Shape of array is (3, 3)


In [36]:
arr2 = np.array([[1,2,5]])
print(arr2)
print("Dimensions of array are:",arr2.ndim)
print("Shape of array is", arr2.shape)

[[1 2 5]]
Dimensions of array are: 2
Shape of array is (1, 3)


In [37]:
arr2 = np.array(([1,2,5]))
print(arr2)
print("Dimensions of array are:",arr2.ndim)
print("Shape of array is", arr2.shape)

# tuple + list will not give you result

[1 2 5]
Dimensions of array are: 1
Shape of array is (3,)


In [39]:
arr2 = np.array(((1,2,5)))
print(arr2)
print("Dimensions of array are:",arr2.ndim)
print("Shape of array is", arr2.shape)

# tuple + list will not give you result

[1 2 5]
Dimensions of array are: 1
Shape of array is (3,)


In [40]:
([1,2,5])

[1, 2, 5]

## 3-D dimensional array

In [42]:
# 3 square brackets >> 3-D

arr3 = np.array([[[1,2,3,4,5,6,7]]])
print("Dimensions of array are:",arr3.ndim)
print("Shape of array is", arr3.shape)
print(arr3)

# 3-D array is made up of number of 2-D array

Dimensions of array are: 3
Shape of array is (1, 1, 7)
[[[1 2 3 4 5 6 7]]]


In [43]:
arr3 = np.array([[[1,2],[3,4],[5,6]]])
print("Dimensions of array are:",arr3.ndim)
print("Shape of array is", arr3.shape)
print(arr3)
# shape >> [2D, 1D, 0D] --> (1,3,2)

Dimensions of array are: 3
Shape of array is (1, 3, 2)
[[[1 2]
  [3 4]
  [5 6]]]


In [48]:
arr3 = np.array([[[1,2],[3,4],[5,6]], [[11,12],[13,14],[15,16]], [[10,20],[30,40],[50,60]]])
print("Dimensions of array are:",arr3.ndim)
print("Shape of array is", arr3.shape)
print(arr3)
# shape >> [2D, 1D, 0D] --> (3,3,2)

print("length of array", len(arr3))

Dimensions of array are: 3
Shape of array is (3, 3, 2)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[11 12]
  [13 14]
  [15 16]]

 [[10 20]
  [30 40]
  [50 60]]]
length of array 3


## 4-D dimensional array

In [49]:
# 4 sqaure brackets --> 4 D array

arr4 = np.array([[[[1,2,4,5,6,7]]]])
print("Dimensions of array are:",arr4.ndim)
print("Shape of array is", arr4.shape)   # [3D, 2D, 1D, 0D]
print(arr4)

Dimensions of array are: 4
Shape of array is (1, 1, 1, 6)
[[[[1 2 4 5 6 7]]]]


# Indexing and Slicing

## 1-D

In [51]:
# indexing
arr1 = np.array([1,2,3,4,8])
arr1[4]

8

In [9]:
import os
os.listdir()
os.getcwd()

'E:\\Data Science\\daily Class\\Daily class topics\\Python\\8_30 Numpy'

In [52]:
arr1 = np.array([1,2,3,4,8])
arr1[0]

1

In [53]:
# slicing

arr1 = np.array([10,20,30,40,80,70,60])
arr1[2:6]  #[2,3,4,5]

array([30, 40, 80, 70])

In [54]:
# slicing

arr1 = np.array([10,20,30,40,80,70,60])
arr1[3:5] 

array([40, 80])

In [55]:
# slicing

arr1 = np.array([10,20,30,40,80,70,60])
arr1[4:5] 

array([80])

In [56]:
# reverse the arry

arr1 = np.array([10,20,30,40,80,70,60])
arr1[::-1]

array([60, 70, 80, 40, 30, 20, 10])

In [57]:
arr1 = np.array([10,20,30,40,80,70,60])
arr1[::]

array([10, 20, 30, 40, 80, 70, 60])

In [58]:
arr1 = np.array([10,20,30,40,80,70,60])
arr1[::2]

array([10, 30, 80, 60])

In [59]:
arr1 = np.array([10,20,30,40,80,70,60])
arr1[::3]

array([10, 40, 60])

# 2-D

In [60]:
# indexing

arr2 = np.array([[4,5],[6,7],[8,9]])
arr2

array([[4, 5],
       [6, 7],
       [8, 9]])

In [61]:
arr2 = np.array([[4,5],[6,7],[8,9]])
arr2[0]

array([4, 5])

In [62]:
arr2 = np.array([[4,5],[6,7],[8,9]])
arr2[0][1]

5

In [63]:
arr2 = np.array([[4,5],[6,7],[8,9]])
arr2[2][0]

8

In [65]:
arr2 = np.array([[4,5],[6,7],[8,9]])
print(arr2)
arr2[2,0]

[[4 5]
 [6 7]
 [8 9]]


8

In [67]:
arr2 = np.array([[4,5],[6,7],[8,9]])
# print(arr2)
arr2[1,0]

6

### slicing

In [70]:
arr2 = np.array([[4,5,10],[6,7,20],[8,9,30]])
arr2

array([[ 4,  5, 10],
       [ 6,  7, 20],
       [ 8,  9, 30]])

In [72]:
arr2 = np.array([[4,5,10],[6,7,20],[8,9,30]])
arr2[:,:]  # [No. of rows, No. of columns]

array([[ 4,  5, 10],
       [ 6,  7, 20],
       [ 8,  9, 30]])

In [73]:
arr2 = np.array([[4,5,10],[6,7,20],[8,9,30]])
arr2[:,0:2]  # [All rows, [0th and 1st] column]

array([[4, 5],
       [6, 7],
       [8, 9]])

In [74]:
arr2 = np.array([[4,5,10],[6,7,20],[8,9,30]])
arr2[:,1:2] 

array([[5],
       [7],
       [9]])

In [75]:
arr2 = np.array([[4,5,10],[6,7,20],[8,9,30]])
arr2[:,1]

array([5, 7, 9])

In [77]:
arr2

array([[ 4,  5, 10],
       [ 6,  7, 20],
       [ 8,  9, 30]])

In [76]:
arr2 = np.array([[4,5,10],[6,7,20],[8,9,30]])
arr2[:,0] 

array([4, 6, 8])

In [78]:
arr2 = np.array([[4,5,10],[6,7,20],[8,9,30]])
arr2[1:3,1:3] 

array([[ 7, 20],
       [ 9, 30]])

In [79]:
arr2 = np.array([[4,5,10],[6,7,20],[8,9,30]])
arr2[1:,0] 

array([6, 8])

In [80]:
arr2

array([[ 4,  5, 10],
       [ 6,  7, 20],
       [ 8,  9, 30]])

In [81]:
arr2 = np.array([[4,5,10],[6,7,20],[8,9,30]])
arr2[2,1] 

9

In [82]:
arr2 = np.array([[4,5,10],[6,7,20],[8,9,30]])
arr2[0,:] 

array([ 4,  5, 10])

In [84]:
arr2 = np.array([[4,5,10],[6,7,20],[8,9,30],[10,20,30],[16,17,12], [44,45,10]])
arr2

array([[ 4,  5, 10],
       [ 6,  7, 20],
       [ 8,  9, 30],
       [10, 20, 30],
       [16, 17, 12],
       [44, 45, 10]])

In [86]:
arr2[2:4,0:2]

array([[ 8,  9],
       [10, 20]])

In [87]:
arr2[1:3,1:3]

array([[ 7, 20],
       [ 9, 30]])

In [88]:
arr2[3:,1:]

array([[20, 30],
       [17, 12],
       [45, 10]])

## 3-D

In [93]:
arr3 = np.array([[[2,1],[4,5],[9,7]],[[21,11],[14,15],[19,71]],[[20,10],[40,50],[90,70]]])
print("Dimensions of array are:", arr3.ndim)
print("shape of array is:", arr3.shape)

Dimensions of array are: 3
shape of array is: (3, 3, 2)


In [94]:
# Indexing
arr3 = np.array([[[2,1],[4,5],[9,7]],[[21,11],[14,15],[19,71]],[[20,10],[40,50],[90,70]]])
arr3

array([[[ 2,  1],
        [ 4,  5],
        [ 9,  7]],

       [[21, 11],
        [14, 15],
        [19, 71]],

       [[20, 10],
        [40, 50],
        [90, 70]]])

In [97]:
# Indexing
arr3 = np.array([[[2,1],[4,5],[9,7]],[[21,11],[14,15],[19,71]],[[20,10],[40,50],[90,70]]])
arr3[0][1][0]

4

In [100]:
# Indexing
arr3 = np.array([[[2,1],[4,5],[9,7]],[[21,11],[14,15],[19,71]],[[20,10],[40,50],[90,70]]])
arr3[2,1,1]   # [2-d, 1-D, 0-D]

50

In [101]:
# Indexing
arr3 = np.array([[[2,1],[4,5],[9,7]],[[21,11],[14,15],[19,71]],[[20,10],[40,50],[90,70]]])
arr3[1,0,1]   # [2-d, 1-D, 0-D]

11

In [102]:
# slicing
arr3 = np.array([[[2,1],[4,5],[9,7]],[[21,11],[14,15],[19,71]],[[20,10],[40,50],[90,70]]])
arr3

array([[[ 2,  1],
        [ 4,  5],
        [ 9,  7]],

       [[21, 11],
        [14, 15],
        [19, 71]],

       [[20, 10],
        [40, 50],
        [90, 70]]])

In [104]:
arr3[:, :, :]

array([[[ 2,  1],
        [ 4,  5],
        [ 9,  7]],

       [[21, 11],
        [14, 15],
        [19, 71]],

       [[20, 10],
        [40, 50],
        [90, 70]]])

In [105]:
arr3[1, :, :]

array([[21, 11],
       [14, 15],
       [19, 71]])

In [107]:
arr3[1, :, 1]

array([11, 15, 71])

In [108]:
arr3[1, 1, :]

array([14, 15])

In [111]:
arr3[1,0,:]

array([21, 11])

In [112]:
arr3

array([[[ 2,  1],
        [ 4,  5],
        [ 9,  7]],

       [[21, 11],
        [14, 15],
        [19, 71]],

       [[20, 10],
        [40, 50],
        [90, 70]]])

In [113]:
arr3[2,:,1]

array([10, 50, 70])

In [3]:
import numpy as np
arr3 = np.array([[[2,1,2],[4,5,4],[9,7,9]],[[21,11,21],[14,15,14],[19,71,19]],[[20,10,20],[40,50,40],[90,70,90]]])
arr3

array([[[ 2,  1,  2],
        [ 4,  5,  4],
        [ 9,  7,  9]],

       [[21, 11, 21],
        [14, 15, 14],
        [19, 71, 19]],

       [[20, 10, 20],
        [40, 50, 40],
        [90, 70, 90]]])

In [4]:
arr3.shape

(3, 3, 3)

In [7]:
arr3[1,:2,:2]

array([[21, 11],
       [14, 15]])

In [117]:
arr3

array([[[ 2,  1,  2],
        [ 4,  5,  4],
        [ 9,  7,  9]],

       [[21, 11, 21],
        [14, 15, 14],
        [19, 71, 19]],

       [[20, 10, 20],
        [40, 50, 40],
        [90, 70, 90]]])

In [118]:
arr3[:,:,1]

array([[ 1,  5,  7],
       [11, 15, 71],
       [10, 50, 70]])

# Convert to n-D array

In [119]:
arr1 = np.array([3,4,5,6,7])
print(arr1)
print("Dimensions -->", arr1.ndim)

[3 4 5 6 7]
Dimensions --> 1


In [120]:
arr1 = np.array([3,4,5,6,7], ndmin = 2)
print(arr1)
print("Dimensions -->", arr1.ndim)

[[3 4 5 6 7]]
Dimensions --> 2


In [121]:
arr1 = np.array([3,4,5,6,7], ndmin = 3)
print(arr1)
print("Dimensions -->", arr1.ndim)

[[[3 4 5 6 7]]]
Dimensions --> 3


In [122]:
arr1 = np.array([3,4,5,6,7], ndmin = 4)
print(arr1)
print("Dimensions -->", arr1.ndim)

[[[[3 4 5 6 7]]]]
Dimensions --> 4


In [123]:
arr1 = np.array([[3,4],[5,6],[7,8]], ndmin = 3)
print(arr1)
print("Dimensions -->", arr1.ndim)

[[[3 4]
  [5 6]
  [7 8]]]
Dimensions --> 3


In [124]:
arr1 = np.array([[3,4],[5,6],[7,8]], ndmin = 1)
print(arr1)
print("Dimensions -->", arr1.ndim)

# it will not convert 2D into 1D

[[3 4]
 [5 6]
 [7 8]]
Dimensions --> 2


In [125]:
arr1 = np.array([[3,4],[5,6],[7,8]], ndmin = 4)
print(arr1)
print("Dimensions -->", arr1.ndim)

[[[[3 4]
   [5 6]
   [7 8]]]]
Dimensions --> 4


# Reshape Function

In [ ]:
Used to convert 
    1D --> 2D or vice versa
    1D --> 3D or vice versa
    2D --> 3D or vice versa
    3D --> 4D or vice versa
    
It is according to shape of dimensions of array.
1D shape >> (6,)  >> 6
2D Shape >> (3, 2) >> 6
3D Shape >> (1, 3, 2) >> 6

In [130]:
arr1 = np.array([1,2,4,5,6,7,8,10,20,30,40,45])
arr1.shape

(12,)

In [ ]:
12 Elements -->
2 D >> (1,12), (2,6), (3,4), (4,3), (6,2), (12,1)
3 D >> (1,1,12), (1,2,6), (2,2,3), (6,2,1), (4,3,1)

In [9]:
import numpy as np
arr1 = np.array([1,2,4,5,6,7,8,10,20,30,40,45])
arr1.reshape(2,6)

array([[ 1,  2,  4,  5,  6,  7],
       [ 8, 10, 20, 30, 40, 45]])

In [4]:
arr1 = np.array([1,2,4,5,6,7,8,10,20,30,40,45])
arr1.reshape(3,4)

array([[ 1,  2,  4,  5],
       [ 6,  7,  8, 10],
       [20, 30, 40, 45]])

In [133]:
arr1 = np.array([1,2,4,5,6,7,8,10,20,30,40,45])
arr1.reshape(6,2)

array([[ 1,  2],
       [ 4,  5],
       [ 6,  7],
       [ 8, 10],
       [20, 30],
       [40, 45]])

In [134]:
arr1 = np.array([1,2,4,5,6,7,8,10,20,30,40,45])
arr1.reshape(1,2,6)

array([[[ 1,  2,  4,  5,  6,  7],
        [ 8, 10, 20, 30, 40, 45]]])

In [135]:
arr1 = np.array([1,2,4,5,6,7,8,10,20,30,40,45])
arr1.reshape(2,2,3)

array([[[ 1,  2,  4],
        [ 5,  6,  7]],

       [[ 8, 10, 20],
        [30, 40, 45]]])

In [136]:
arr1 = np.array([1,2,4,5,6,7,8,10,20,30,40,45])
arr1.reshape(4,3,1)

array([[[ 1],
        [ 2],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [10],
        [20]],

       [[30],
        [40],
        [45]]])

In [20]:
arr1 = np.array([1,2,4,5,6,7,8,10,20,30,40,45])
arr1.reshape(4,1,3)

array([[[ 1,  2,  4]],

       [[ 5,  6,  7]],

       [[ 8, 10, 20]],

       [[30, 40, 45]]])

In [139]:
arr4 = np.array([[[ 1,  2,  4]],

       [[ 5,  6,  7]],

       [[ 8, 10, 20]],

       [[30, 40, 45]]])
arr4

array([[[ 1,  2,  4]],

       [[ 5,  6,  7]],

       [[ 8, 10, 20]],

       [[30, 40, 45]]])

In [140]:
arr4.reshape(4,3)

array([[ 1,  2,  4],
       [ 5,  6,  7],
       [ 8, 10, 20],
       [30, 40, 45]])

In [141]:
arr4.reshape(12,)

array([ 1,  2,  4,  5,  6,  7,  8, 10, 20, 30, 40, 45])

# Flattern the list

In [1]:
lst = [[1,2,3,4],[10,20,30,40], [11,12,13,14]]
lst

[[1, 2, 3, 4], [10, 20, 30, 40], [11, 12, 13, 14]]

In [4]:
import numpy as np
arr1 = np.array(lst)
new_arr = arr1.reshape(12,)
new_arr

array([ 1,  2,  3,  4, 10, 20, 30, 40, 11, 12, 13, 14])

In [148]:
new_arr.tolist()

[1, 2, 3, 4, 10, 20, 30, 40, 11, 12, 13, 14]

In [147]:
type(new_arr.tolist())

list

In [149]:
lst = [[1,2,3,4],[10,20,30,40], [11,12,13,14]]
lst

[[1, 2, 3, 4], [10, 20, 30, 40], [11, 12, 13, 14]]

In [10]:
arr1 = np.array(lst)
new_arr = arr1.reshape(-1)
new_arr.tolist()

[1, 2, 3, 4, 10, 20, 30, 40, 11, 12, 13, 14]

In [154]:
lst = [[1,2,3,4,5],
       [10,20,30,40,8],
       [11,12,13,14,7],
       [10,20,30,40,8],
       [10,20,30,40,8]]
arr1 = np.array(lst)
len(arr1)

3

In [6]:
arr1 = np.array([1,2,3,4,5,6,7])
arr1.reshape(7,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [7]:
arr1 = np.array([1,2,3,4,5,6,7])
arr1.reshape(1,7,1)

array([[[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7]]])

In [8]:
arr1 = np.array([1,2,3,4,5,6,7])
arr1.reshape(1,1,7)

array([[[1, 2, 3, 4, 5, 6, 7]]])