# Numpy Functions

## 1. np.reshape(m,n)

## 2. np.zeros()

In [ ]:
Syntax:
    np.zeros(shape, dtype = 'int'/'float')
    
Returns an array of zero values
- use in weight initialization in deep learning algorithm.
- Target variable in machine learning
    Its value either '0' or '1'

In [4]:
import numpy as np
arr = np.zeros(5)   # float
arr

array([0., 0., 0., 0., 0.])

In [5]:
arr = np.zeros(10, dtype = 'int')   # float
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
arr = np.zeros([2,3], dtype = 'int')   # float
arr

array([[0, 0, 0],
       [0, 0, 0]])

In [7]:
arr = np.zeros([3,3], dtype = 'int')   # float
arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [8]:
np.round(5)

5

In [9]:
arr = np.zeros([4,5], dtype = 'int')   # float
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## 3. np.ones()

In [10]:
syntax:
    np.ones(shape, dtype = 'int'/'float')

SyntaxError: invalid syntax (1085710226.py, line 1)

In [11]:
arr = np.ones(10, dtype = 'int')
arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [12]:
arr = np.ones([2,3], dtype = 'int')
arr

array([[1, 1, 1],
       [1, 1, 1]])

In [13]:
arr = np.ones([3,3], dtype = 'int')
arr

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [14]:
arr = np.ones([4,5], dtype = 'int')
arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### dataframe

In [15]:
import pandas as pd

In [16]:
df = pd.DataFrame(arr)
df

0  1  2  3  4
0  1  1  1  1  1
1  1  1  1  1  1
2  1  1  1  1  1
3  1  1  1  1  1

## 4. arange

In [ ]:
- simillar to range function
syntax:
    np.arange()

In [14]:
list(range(10,20))

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [15]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [2]:
a= range(10,20)
type(a)

range

In [16]:
np.arange(10,31)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30])

In [17]:
np.arange(10,31,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [5]:
import numpy as np
arr = np.arange(20,10,-1, dtype='float')
print(arr)
arr.shape

# possibilities
5,2
2,5
1,10
10,1

[20. 19. 18. 17. 16. 15. 14. 13. 12. 11.]


(10, 1)

In [21]:
arr.reshape(2,5)

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11]])

In [22]:
arr.reshape(5,2)

array([[20, 19],
       [18, 17],
       [16, 15],
       [14, 13],
       [12, 11]])

## 5. linspace()

In [ ]:
synatx:
    np.linspace(start, end, num=50, retstep = True)

In [6]:
import numpy as np
arr1 = np.linspace(1,50, num=25, retstep= True)
arr1

# retstep = (50 - 1) / (50 - 1)

(array([ 1.        ,  3.04166667,  5.08333333,  7.125     ,  9.16666667,
        11.20833333, 13.25      , 15.29166667, 17.33333333, 19.375     ,
        21.41666667, 23.45833333, 25.5       , 27.54166667, 29.58333333,
        31.625     , 33.66666667, 35.70833333, 37.75      , 39.79166667,
        41.83333333, 43.875     , 45.91666667, 47.95833333, 50.        ]),
 2.0416666666666665)

In [25]:
arr1 = np.linspace(1,100, num=10, retstep= True)
arr1
# [1,.......,100]

# retstep = 100-1 / 10-1

(array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.]), 11.0)

In [26]:
arr1 = np.linspace(1,100, num=10, retstep= False)
arr1

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [27]:
arr1 = np.linspace(1,50, num=10, retstep= True)
arr1

(array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
        28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ]),
 5.444444444444445)

In [28]:
arr1 = np.linspace(1,50, num=20, retstep= True)
arr1

# returnstepsize = 2.5789473684210527

(array([ 1.        ,  3.57894737,  6.15789474,  8.73684211, 11.31578947,
        13.89473684, 16.47368421, 19.05263158, 21.63157895, 24.21052632,
        26.78947368, 29.36842105, 31.94736842, 34.52631579, 37.10526316,
        39.68421053, 42.26315789, 44.84210526, 47.42105263, 50.        ]),
 2.5789473684210527)

In [29]:
# create dictionary

dict1 = {"zeros": np.zeros(10),
        "ones": np.ones(10),
        "Arange":np.arange(20,30),
        "Linspace":np.linspace(100,200, num=10)}

dict1

{'zeros': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 'ones': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 'Arange': array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),
 'Linspace': array([100.        , 111.11111111, 122.22222222, 133.33333333,
        144.44444444, 155.55555556, 166.66666667, 177.77777778,
        188.88888889, 200.        ])}

In [30]:
# create a data frame
import pandas as pd
df = pd.DataFrame(dict1)
df

zeros  ones  Arange    Linspace
0    0.0   1.0      20  100.000000
1    0.0   1.0      21  111.111111
2    0.0   1.0      22  122.222222
3    0.0   1.0      23  133.333333
4    0.0   1.0      24  144.444444
5    0.0   1.0      25  155.555556
6    0.0   1.0      26  166.666667
7    0.0   1.0      27  177.777778
8    0.0   1.0      28  188.888889
9    0.0   1.0      29  200.000000

In [31]:
df['Python'] = [1,2,3,4,5,6,7,8,9,10]
df

zeros  ones  Arange    Linspace  Python
0    0.0   1.0      20  100.000000       1
1    0.0   1.0      21  111.111111       2
2    0.0   1.0      22  122.222222       3
3    0.0   1.0      23  133.333333       4
4    0.0   1.0      24  144.444444       5
5    0.0   1.0      25  155.555556       6
6    0.0   1.0      26  166.666667       7
7    0.0   1.0      27  177.777778       8
8    0.0   1.0      28  188.888889       9
9    0.0   1.0      29  200.000000      10

In [32]:
df['Linspace2'] = np.linspace(500,1000, num=10)
df

zeros  ones  Arange    Linspace  Python    Linspace2
0    0.0   1.0      20  100.000000       1   500.000000
1    0.0   1.0      21  111.111111       2   555.555556
2    0.0   1.0      22  122.222222       3   611.111111
3    0.0   1.0      23  133.333333       4   666.666667
4    0.0   1.0      24  144.444444       5   722.222222
5    0.0   1.0      25  155.555556       6   777.777778
6    0.0   1.0      26  166.666667       7   833.333333
7    0.0   1.0      27  177.777778       8   888.888889
8    0.0   1.0      28  188.888889       9   944.444444
9    0.0   1.0      29  200.000000      10  1000.000000

In [34]:
np.linspace(5000,1000, num=10, retstep=True)

(array([5000.        , 4555.55555556, 4111.11111111, 3666.66666667,
        3222.22222222, 2777.77777778, 2333.33333333, 1888.88888889,
        1444.44444444, 1000.        ]),
 -444.44444444444446)

## 6. eye()

In [ ]:
It will return 2D array with diagonal matrix

syntax:
    np.eye(shape, dtype= 'int')
    

In [2]:
import numpy as np
np.eye(3, dtype = 'int')
# identity matrix 3 * 3

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [38]:
np.eye(5, dtype = 'int')
# identity matrix 5 * 5

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [39]:
np.eye(5,4, dtype = 'int')
#  5 * 4

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

In [40]:
np.eye(2,4, dtype = 'int')
#  2 * 4

array([[1, 0, 0, 0],
       [0, 1, 0, 0]])

## 7. identity()

In [ ]:
It will return an 2D array with ones o diagonal

synatx:
    np.identity(n, dtype="int")
    
    matrix of order n * n

In [3]:
np.identity(3, dtype= 'int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [136]:
np.identity(4, dtype= 'int')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

## 8. random()

In [ ]:
It is used for generating random numbers in an array.

Subfunctions:
    1. rand()
    2. randint()
    3. randn()
    4. ranf()

#### 8.1 random.rand()

In [6]:
arr1 = np.random.rand(5)
arr1

array([0.50197151, 0.02379953, 0.87226985, 0.07105993, 0.8155693 ])

In [ ]:
np.

In [85]:
arr1 = np.random.rand(5,3)
arr1

array([[0.01913752, 0.56644776, 0.26188762],
       [0.85390264, 0.78397364, 0.4360929 ],
       [0.54032805, 0.59601333, 0.2378395 ],
       [0.32324857, 0.61018769, 0.34809219],
       [0.65790195, 0.9603407 , 0.21793333]])

In [86]:
arr1 = np.random.rand(3,3)
arr1

array([[0.69544348, 0.52340311, 0.49417222],
       [0.64598582, 0.60575099, 0.03937801],
       [0.77702594, 0.66647782, 0.71128755]])

#### 8.2 random.randint()

In [ ]:
Returns random integers between given shape

syntax:
    np.random.randint(low, high, size = , dtype = )
    
    size = size of an array
    
    

In [87]:
array = np.random.randint(1,50, size = 5)
array

array([42, 15, 41,  5, 18])

In [101]:
array = np.random.randint(40,50, size = 10)
array

array([49, 49, 48, 46, 49, 47, 42, 47, 42, 44])

In [102]:
array = np.random.randint(25,50, size = (3,3))
array

array([[47, 36, 25],
       [33, 30, 27],
       [31, 44, 36]])

In [103]:
array = np.random.randint(11,20, size = (3,3))
array

array([[13, 16, 15],
       [17, 19, 15],
       [14, 18, 17]])

In [104]:
array = np.random.randint(11,20, size = (3,3,3))
array

array([[[11, 11, 13],
        [19, 18, 12],
        [11, 18, 19]],

       [[16, 18, 17],
        [15, 14, 16],
        [15, 19, 11]],

       [[18, 13, 19],
        [13, 13, 12],
        [19, 14, 12]]])

#### 8.3 random.randn()

In [ ]:
random normalize
returns normally distributed values

standard normal distribution >> Bell shape curve/ Gausian Curve

syntax:
    np.random.randn(shape)

In [116]:
np.random.randn(5)

array([ 0.0841035 ,  0.05072388, -0.99720537,  1.41371068, -1.50430588])

In [117]:
np.random.randn(5,3)

array([[ 0.21277665,  1.15174583, -0.17831501],
       [ 0.54892626,  0.09580482,  0.77769393],
       [ 0.13198712,  1.46829907, -0.4814915 ],
       [ 0.0374234 , -2.47953713,  0.19675818],
       [-0.84311392,  1.21002455, -1.55520311]])

In [118]:
np.random.randn(5,3,2)

array([[[-1.04140741e+00,  1.21736779e+00],
        [-1.68765897e-01, -5.05867147e-01],
        [ 1.43490920e-02,  3.48789108e-01]],

       [[ 5.47644369e-02,  5.29995432e-02],
        [-3.54363290e-04,  7.45626996e-01],
        [ 6.29238800e-01, -9.26129324e-01]],

       [[ 9.11507631e-02, -1.49024065e-01],
        [ 1.43588661e+00, -7.69108055e-02],
        [ 1.25849954e+00, -1.18897562e-01]],

       [[-7.88570601e-01,  2.04872116e+00],
        [ 5.50160757e-01,  8.46636299e-02],
        [ 2.34258055e+00,  1.20115860e+00]],

       [[ 7.19752254e-01,  7.38505771e-01],
        [ 1.53630188e+00,  2.42872465e+00],
        [ 7.60721625e-01,  1.47250376e+00]]])

#### 8.4 random.ranf()

In [ ]:
Returns random float in between 0 to 1 interval

syntax:
    np.random.ranf(shape)
    np.random.random_sample(shape)

In [119]:
np.random.ranf(5)

array([0.11737394, 0.72073445, 0.8917298 , 0.77552039, 0.19691278])

In [121]:
np.random.ranf((5,3))

array([[0.43309656, 0.24359913, 0.73955579],
       [0.4011194 , 0.36314683, 0.40586087],
       [0.12470711, 0.05388314, 0.20098959],
       [0.70875615, 0.30800995, 0.24392008],
       [0.20301178, 0.62801065, 0.18509925]])

In [122]:
np.random.random_sample((4,3))

array([[0.66661995, 0.24660884, 0.82535022],
       [0.90625216, 0.32069514, 0.83646578],
       [0.22404999, 0.04213746, 0.70634336],
       [0.86098363, 0.98421161, 0.83289425]])

## 9. sort

In [ ]:
syntax:
    np.sort(array)
    
    axis = 0 # It will sorted rowwise
    axis = 1 # It will sorted columnwise

In [123]:
# create an array

arr = np.random.randint(10,20, size=10)
arr

array([19, 15, 14, 18, 10, 19, 17, 12, 12, 10])

In [124]:
np.sort(arr)

array([10, 10, 12, 12, 14, 15, 17, 18, 19, 19])

In [3]:
arr = np.random.randint(10,20, size=(3,4))
arr

array([[19, 14, 19, 12],
       [19, 18, 12, 13],
       [10, 17, 14, 16]])

In [4]:
arr   # original matrix

array([[19, 14, 19, 12],
       [19, 18, 12, 13],
       [10, 17, 14, 16]])

In [5]:
np.sort(arr, axis = 0)  # Rowwise

array([[10, 14, 12, 12],
       [19, 17, 14, 13],
       [19, 18, 19, 16]])

In [134]:
np.sort(arr, axis = 1)  # columnwise

array([[11, 11, 12, 14],
       [11, 13, 13, 18],
       [10, 10, 13, 18]])

In [ ]:
# Axis = 0 >> row
# axis = 1 >> Column