# **Creating the array using the numpy array**

## Import the numpy library

In [64]:
import numpy as np 

## Zero dimention array

In [57]:
array0=np.array(5)
print(array0,type(array0),array0.ndim)

5 <class 'numpy.ndarray'> 0


## 1 dimention array

In [55]:
array1=np.array([5])
print(array1,type(array1),array1.ndim)

[5] <class 'numpy.ndarray'> 1


## 2 dimention array

In [72]:
array2=np.array([[5,7],[6,8]])
print(array2,type(array2),array2.ndim)
print(array2.shape)

[[5 7]
 [6 8]] <class 'numpy.ndarray'> 2
(2, 2)


## 3 dimention array

In [73]:
array3= np.array([[[5,8],[6,9]],[[5,3],[6,7]]])
print(array3,type(array3),array3.ndim)
print(array3.shape)


[[[5 8]
  [6 9]]

 [[5 3]
  [6 7]]] <class 'numpy.ndarray'> 3
(2, 2, 2)


## 4 dimentional array

In [69]:
array4=np.array([[[[1],[2]],[[1],[2]]],[[[1],[2]],[[1],[2]]]])
print(array4,type(array4),array4.ndim)
print(array4.shape)


# 1st dimension: Groups of 3D arrays.
# 2nd dimension: Rows of 2D matrices.
# 3rd dimension: Columns of 1D arrays.
# 4th dimension: Individual elements in the arrays.


[[[[1]
   [2]]

  [[1]
   [2]]]


 [[[1]
   [2]]

  [[1]
   [2]]]] <class 'numpy.ndarray'> 4
(2, 2, 2, 1)


## checking the shape of the array 

In [67]:
print(array0.shape)
print(array1.shape)
print(array2.shape)
print(array3.shape)
print(array4.shape)

()
(1,)
(2, 1)
(2, 2, 1)
(2, 2, 2, 1)


In [88]:
array4[1][1]

array([[1],
       [2]])

## Slicing in the numpy array

import numpy as raand
arr1=np.array([2,4,6,8,10])
arr1[::2]

In [12]:

arr1[2:5]

array([ 6,  8, 10])

In [13]:
# step size 
arr1[::2]

array([ 2,  6, 10])

In [25]:
array2=np.array([[5,7],[6,8]])
array2[0][1]

7

In [27]:
array3=np.array([[[5,7,8],[6,8,9]],[[9,10,23],[11,12,15]]])

In [28]:
array3[1][1][1]

12

In [36]:
array4=np.array([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],[[[13,14,15],[16,17,18]],[[19,20,21],[22,23,24]]]])

In [37]:
array4.shape

(2, 2, 2, 3)

In [45]:
array4[1][0][1][0:2]

array([16, 17])

In [55]:
import numpy as np
arr33=np.array([[[2,1,2],[4,5,4],[9,7,9]],[[21,11,21],[14,15,16],[19,71,19]],[[20,10,20],[40,50,40],[90,70,90]]])
arr33

array([[[ 2,  1,  2],
        [ 4,  5,  4],
        [ 9,  7,  9]],

       [[21, 11, 21],
        [14, 15, 16],
        [19, 71, 19]],

       [[20, 10, 20],
        [40, 50, 40],
        [90, 70, 90]]])

In [9]:
arr33[1,:2,:2]

array([[21, 11],
       [14, 15]])

In [10]:
arr33.shape

(3, 3, 3)

In [11]:
arr33[1][:2][:2]

array([[21, 11, 21],
       [14, 15, 16]])

In [12]:
arr33[1][1][0:2]

array([14, 15])

In [13]:
arr33[1][0][0:2]

array([21, 11])

In [14]:
arr33

array([[[ 2,  1,  2],
        [ 4,  5,  4],
        [ 9,  7,  9]],

       [[21, 11, 21],
        [14, 15, 16],
        [19, 71, 19]],

       [[20, 10, 20],
        [40, 50, 40],
        [90, 70, 90]]])

In [16]:
arr33[0,1:3,1:3]

array([[5, 4],
       [7, 9]])

In [33]:

new_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(new_arr,new_arr.shape)
reshaped_new_arr = new_arr.reshape(3, 3)
print("Reshaped array :\n",reshaped_new_arr)

[1 2 3 4 5 6 7 8 9] (9,)
Reshaped array :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
new_re=reshaped_new_arr.reshape(9,)
print(new_re,new_re.ndim)

[1 2 3 4 5 6 7 8 9] 1


In [35]:
new_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
new_arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])