# **Creating the array using the numpy array**

## Import the numpy library

In [64]:
import numpy as np 

## Zero dimention array

In [57]:
array0=np.array(5)
print(array0,type(array0),array0.ndim)

5 <class 'numpy.ndarray'> 0


## 1 dimention array

In [55]:
array1=np.array([5])
print(array1,type(array1),array1.ndim)

[5] <class 'numpy.ndarray'> 1


## 2 dimention array

In [72]:
array2=np.array([[5,7],[6,8]])
print(array2,type(array2),array2.ndim)
print(array2.shape)

[[5 7]
 [6 8]] <class 'numpy.ndarray'> 2
(2, 2)


## 3 dimention array

In [73]:
array3= np.array([[[5,8],[6,9]],[[5,3],[6,7]]])
print(array3,type(array3),array3.ndim)
print(array3.shape)


[[[5 8]
  [6 9]]

 [[5 3]
  [6 7]]] <class 'numpy.ndarray'> 3
(2, 2, 2)


## 4 dimentional array

In [69]:
array4=np.array([[[[1],[2]],[[1],[2]]],[[[1],[2]],[[1],[2]]]])
print(array4,type(array4),array4.ndim)
print(array4.shape)


# 1st dimension: Groups of 3D arrays.
# 2nd dimension: Rows of 2D matrices.
# 3rd dimension: Columns of 1D arrays.
# 4th dimension: Individual elements in the arrays.


[[[[1]
   [2]]

  [[1]
   [2]]]


 [[[1]
   [2]]

  [[1]
   [2]]]] <class 'numpy.ndarray'> 4
(2, 2, 2, 1)


## checking the shape of the array 

In [67]:
print(array0.shape)
print(array1.shape)
print(array2.shape)
print(array3.shape)
print(array4.shape)

()
(1,)
(2, 1)
(2, 2, 1)
(2, 2, 2, 1)


In [88]:
array4[1][1]

array([[1],
       [2]])

## Slicing in the numpy array

import numpy as raand
arr1=np.array([2,4,6,8,10])
arr1[::2]

In [12]:

arr1[2:5]

array([ 6,  8, 10])

In [13]:
# step size 
arr1[::2]

array([ 2,  6, 10])

In [25]:
array2=np.array([[5,7],[6,8]])
array2[0][1]

7

In [27]:
array3=np.array([[[5,7,8],[6,8,9]],[[9,10,23],[11,12,15]]])

In [28]:
array3[1][1][1]

12

In [36]:
array4=np.array([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],[[[13,14,15],[16,17,18]],[[19,20,21],[22,23,24]]]])

In [37]:
array4.shape

(2, 2, 2, 3)

In [45]:
array4[1][0][1][0:2]

array([16, 17])

In [55]:
import numpy as np
arr33=np.array([[[2,1,2],[4,5,4],[9,7,9]],[[21,11,21],[14,15,16],[19,71,19]],[[20,10,20],[40,50,40],[90,70,90]]])
arr33

array([[[ 2,  1,  2],
        [ 4,  5,  4],
        [ 9,  7,  9]],

       [[21, 11, 21],
        [14, 15, 16],
        [19, 71, 19]],

       [[20, 10, 20],
        [40, 50, 40],
        [90, 70, 90]]])

In [9]:
arr33[1,:2,:2]

array([[21, 11],
       [14, 15]])

In [10]:
arr33.shape

(3, 3, 3)

In [11]:
arr33[1][:2][:2]

array([[21, 11, 21],
       [14, 15, 16]])

In [12]:
arr33[1][1][0:2]

array([14, 15])

In [13]:
arr33[1][0][0:2]

array([21, 11])

In [14]:
arr33

array([[[ 2,  1,  2],
        [ 4,  5,  4],
        [ 9,  7,  9]],

       [[21, 11, 21],
        [14, 15, 16],
        [19, 71, 19]],

       [[20, 10, 20],
        [40, 50, 40],
        [90, 70, 90]]])

In [16]:
arr33[0,1:3,1:3]

array([[5, 4],
       [7, 9]])

In [33]:
new_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(new_arr,new_arr.shape)
reshaped_new_arr = new_arr.reshape(3, 3)
print("Reshaped array :\n",reshaped_new_arr)

[1 2 3 4 5 6 7 8 9] (9,)
Reshaped array :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
new_re=reshaped_new_arr.reshape(9,)
print(new_re,new_re.ndim)

[1 2 3 4 5 6 7 8 9] 1


In [35]:
new_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
new_arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [3]:
# Create a 4-dimensional array
import numpy as np
array4d = np.arange(1, 33).reshape(2, 2, 2, 4)
print("Original 4D array:\n", array4d)

# Reshape the 4-dimensional array

reshaped_array4d = array4d.reshape(4, 4, 2)
print("\nReshaped array:\n", reshaped_array4d)

Original 4D array:
 [[[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 10 11 12]
   [13 14 15 16]]]


 [[[17 18 19 20]
   [21 22 23 24]]

  [[25 26 27 28]
   [29 30 31 32]]]]

Reshaped array:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]

 [[25 26]
  [27 28]
  [29 30]
  [31 32]]]


In [4]:
# Create a 3-dimensional array
array3d = np.arange(1, 25).reshape(3, 2, 4)
print("Original 3D array:\n", array3d)

# Reshape the 3-dimensional array into a 2-dimensional array
reshaped_array2d = array3d.reshape(6, 4)
print("\nReshaped 2D array:\n", reshaped_array2d)

Original 3D array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]

Reshaped 2D array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [7]:
array5=np.array([[5,6,3,1,4],[6,9,8,5,4]])

In [8]:
def my_generator():
    yield 1
    yield 2
    yield 3

# Using the generator
gen = my_generator()
for value in gen:
    print(value)

1
2
3


In [9]:
# Original class
class MyClass:
    def greet(self):
        return "Hello, world!"

# Monkey patching the greet method
def new_greet(self):
    return "Hello, monkey patched world!"

MyClass.greet = new_greet

# Using the patched class
obj = MyClass()
print(obj.greet())  # Output: Hello, monkey patched world!

Hello, monkey patched world!


In [40]:
tup={6,5,9,8}
tupi=np.array(tup)

In [41]:
tupi

array({8, 9, 5, 6}, dtype=object)

In [42]:
type(tup)

set

In [43]:
type(tupi)

numpy.ndarray

In [44]:
tupi.ndim

0

In [46]:
def read_large_file(file_path):
    with open(file_path, 'r') as file:
        for line in file:
            yield line

# Usage
for line in read_large_file('file.txt'):
    print(line)

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor

 incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud 

 exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure 

 dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur 

 sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.



Curabitur pretium tincidunt lacus. Nulla gravida orci a odio. Nullam varius, turpis et commodo pharetra, est eros bibendum elit,


In [58]:
def simple_generator():
    yield 1
    yield 2
    yield 3

# Using the generator
for i in simple_generator():
    print(i)

1
2
3


In [65]:
# line space
# syntax = np.linespace(start,end,num=50,retstep=True)
import numpy as np 
arr6=np.linspace(1,50,num=50,retstep=True,dtype=int,axis=)

In [62]:
arr6

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]),
 1.0)

In [67]:
import numpy as np

# Generate 5 evenly spaced numbers between 2.0 and 3.0
result = np.linspace(2.0, 3.0, num=5,dtype=int)
print(result)  # Output: [2.  , 2.25, 2.5 , 2.75, 3.  ]

[2 2 2 2 3]


In [68]:
# eye matrix

# syntax=np.eye(shape,dtype=int)

import numpy as np

np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [71]:
#identity matrix
#syntax= np.identit(n,dtype=int)

np.identity(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [97]:
# Subfunctions in the random library

# ran
# randint
# randn
# ranf


import numpy as np

print("random 5 values from 0 to 1 :",np.random.rand(5))
print("random values from start to end :",np.random.randint(1,10,size=10))
print("random value array : ",np.random.randn(2,4))
print("random value array : ",np.random.randn(2,4))
print("random value array : ",np.random.ranf((2,6)))

random 5 values from 0 to 1 : [0.09801827 0.76856605 0.33573655 0.42970606 0.17149026]
random values from start to end : [2 9 4 6 7 2 1 9 3 8]
random value array :  [[-0.45123081 -0.57866073  0.59814822 -0.97924312]
 [-1.72111278  1.40822392 -0.52117154  0.8903413 ]]
random value array :  [[ 0.70293984 -0.99123526 -0.1423259  -1.29820103]
 [-0.94170689 -2.13160328 -2.33783585 -0.03145288]]
random value array :  [[0.21235802 0.27301538 0.26702863 0.66080455 0.84706989 0.9268885 ]
 [0.23021831 0.02060314 0.96333379 0.86221991 0.29270408 0.85964306]]


In [103]:
# SOrt Function
# np.sort(array)
newarr=np.array([[9,6,8,7,6,8],[1,2,5,4,3,5]])
np.sort(newarr,axis=1)

array([[6, 6, 7, 8, 8, 9],
       [1, 2, 3, 4, 5, 5]])

In [113]:
# append:
# np.append(arrayname,value,axis=None)
array7=np.random.randint(1,10,size=10)
np.append(array7,[5,3,6])

array([5, 5, 6, 6, 7, 4, 3, 6, 3, 8, 5, 3, 6])

In [111]:
array7

array([7, 3, 2, 4, 8, 5, 1, 2, 4, 2])

In [38]:
# concat function in Python 
#syntax : np.concatenate(a1,a2,a3,.....)
import numpy as np
# Create 3 three-dimensional arrays
array1 = np.random.randint(1, 10, size=(2, 3, 4),dtype=int)
array2 = np.random.randint(10, 20, size=(2, 3, 4),dtype=int)
array3 = np.random.randint(20, 30, size=(2, 3, 4),dtype=int)

array4=np.concatenate((array1,array2,array3),axis=0)
print(array4,array4.ndim,array4.shape)


[[[ 5  8  5  4]
  [ 6  6  6  7]
  [ 5  8  8  9]]

 [[ 8  9  6  8]
  [ 1  5  5  8]
  [ 5  4  2  3]]

 [[11 14 19 13]
  [12 15 14 17]
  [15 15 10 13]]

 [[15 14 14 13]
  [13 14 17 12]
  [18 16 14 10]]

 [[22 21 26 27]
  [29 27 27 26]
  [21 20 21 28]]

 [[21 28 23 28]
  [21 26 21 22]
  [21 28 25 22]]] 3 (6, 3, 4)


In [24]:
# Creating the array with tuple

li=[5,6,3,9,8,7,4]
import numpy as np

tup=(56,4,23,4,7,5)

array1=np.array(li)
array2=np.array(tup)

In [26]:
print(array2,type(array2))

[56  4 23  4  7  5] <class 'numpy.ndarray'>


In [31]:
array1


array([[[1, 7, 8, 3],
        [5, 5, 8, 3],
        [3, 2, 1, 5]],

       [[5, 4, 9, 2],
        [5, 5, 9, 4],
        [3, 5, 5, 3]]])

In [32]:
array2

array([[[10, 15, 17, 14],
        [15, 16, 16, 16],
        [11, 19, 14, 16]],

       [[16, 16, 14, 13],
        [12, 10, 14, 13],
        [19, 12, 11, 11]]])

In [50]:
# DIfference between append and concat

import numpy as np

array4=np.concatenate((array1,array2,array3))


array4

array([[[ 5,  8,  5,  4],
        [ 6,  6,  6,  7],
        [ 5,  8,  8,  9]],

       [[ 8,  9,  6,  8],
        [ 1,  5,  5,  8],
        [ 5,  4,  2,  3]],

       [[11, 14, 19, 13],
        [12, 15, 14, 17],
        [15, 15, 10, 13]],

       [[15, 14, 14, 13],
        [13, 14, 17, 12],
        [18, 16, 14, 10]],

       [[22, 21, 26, 27],
        [29, 27, 27, 26],
        [21, 20, 21, 28]],

       [[21, 28, 23, 28],
        [21, 26, 21, 22],
        [21, 28, 25, 22]]])

In [45]:
array1

array([[[5, 8, 5, 4],
        [6, 6, 6, 7],
        [5, 8, 8, 9]],

       [[8, 9, 6, 8],
        [1, 5, 5, 8],
        [5, 4, 2, 3]]])

In [40]:
array2

array([[[11, 14, 19, 13],
        [12, 15, 14, 17],
        [15, 15, 10, 13]],

       [[15, 14, 14, 13],
        [13, 14, 17, 12],
        [18, 16, 14, 10]]])

In [41]:
array3

array([[[22, 21, 26, 27],
        [29, 27, 27, 26],
        [21, 20, 21, 28]],

       [[21, 28, 23, 28],
        [21, 26, 21, 22],
        [21, 28, 25, 22]]])

In [58]:
# One-dimensional array
one_d_array = np.array([1, 2, 3, 4, 5])
print("One-dimensional array:\n", one_d_array)

# Two-dimensional array
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])
print("\nTwo-dimensional array:\n", two_d_array)

# Three-dimensional array
three_d_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("\nThree-dimensional array:\n", three_d_array)

One-dimensional array:
 [1 2 3 4 5]

Two-dimensional array:
 [[1 2 3]
 [4 5 6]]

Three-dimensional array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [61]:
for i in one_d_array:
    print("value : ", i+20)

value :  21
value :  22
value :  23
value :  24
value :  25


In [62]:
for i  in two_d_array:
    print("value : ", i+20)

value :  [21 22 23]
value :  [24 25 26]


In [64]:
for i in three_d_array:
    print("value : ", i)

value :  [[1 2 3]
 [4 5 6]]
value :  [[ 7  8  9]
 [10 11 12]]


In [68]:
#for loop in the 1+ dimentional array

two_d_array

for i in np.nditer(two_d_array):
    print("Value is ", i)

Value is  1
Value is  2
Value is  3
Value is  4
Value is  5
Value is  6


In [69]:
for index, value in enumerate(two_d_array):
    print(f"Index: {index}, Value: {value}")

Index: 0, Value: [1 2 3]
Index: 1, Value: [4 5 6]


In [28]:
class Solution:
    def lltonum(self,head):
        num=""
        cur=head
        while cur!=None:
            num=num+str(cur.data)
            cur=cur.next
        return num
        
    def addTwoLists(self, num1, num2):
        n1=self.lltonum(num1)
        n2=self.lltonum(num2)
        print(n1)
        print(n2)
        return int(n1)+int(n2)
        


In [29]:
solution = Solution()
sum = solution.addTwoLists(num1=head, num2=head2)
print(sum)

15545
55545
71090


In [2]:
class Node:
    def __init__(self, data):
        self.data = data
        self.next = None
        

In [5]:
# Define the Node class
class Node:
    def __init__(self, data):
        self.data = data
        self.next = None

# Create 5 nodes
head = Node(1)
second = Node(2)
third = Node(3)
fourth = Node(4)
fifth = Node(5)

# Link the nodes
head.next = second
second.next = third
third.next = fourth
fourth.next = fifth



In [26]:
# Create 5 nodes
head2 = Node(5)
second = Node(5)
third = Node(5)
fourth = Node(4)
fifth = Node(5)

# Link the nodes
head2.next = second
second.next = third
third.next = fourth
fourth.next = fifth


In [27]:
head2.next.data

5